juji-io/datalevin

- src/datalevin/storage.clj
- src/datalevin/util.cljc
Addresses #20, works on windows, should be identical to existing behavior on linux/osx.  There are places throughout the benchmark and example code where invocations are hard coded to "/tmp" , which could be changed out with u/tmp-dir if desired.
> Added portable temporary directory default.

- src/datalevin/util.cljc
Result of previous PR merge unintentionally broke windows support and fixed linux :)
The problem was that windows path is returned with a separator at the end, while linux (and assumably osx) is not.
The merged PR inject an additional separator into the tmp-dir function, which created a duplicate separator on windows, but
corrected the behavior on linux.
This patch normalizes the return for value of +tmp+ to ensure it has a separator at the end, and just turns tmp-dir into a function that appends the directory name to +tmp+.  We could do fancy portable path parsing, but it seems easier to constrain the function to expect a single directory name as opposed to a possible non-portable path.
For the sake of cljc portability, I also wrapped the existing java stuff in reader conditionals and …
> Hopefully final fix to minor portability issue

- .github/workflows/build.yml
Hi @huahaiy,
I saw your blog post on compiling Datalevin with GraalVM and I am quite impressed.  In response, I've rigged up a GH action that you might find useful that builds Datalevin native for mac/linux. Right now this script only builds the binaries but it would be straightforward to auto-deposit built binaries if its  useful to you.
Previous Successful Build:  [Here](https://github.com/zachcp/datalevin/runs/1884595817?check_suite_focus=true)
zach cp
> Create a GH-Action for Building DataLevin Native on OSX & Linux

- src/datalevin/core.cljc
- src/datalevin/search.clj
- test/datalevin/core_test.cljc
In addition to the tools functions, this adds a `:query-analyzer` in addition to `analyzer` without breaking compatibility, mostly because it is absolutely needed to support efficient autocomplete, and I think it is a great possible application for datalevin...
A remaining problem here is that, from my reading of the code `inter-fn` cannot nest right now, which means you cannot use fn producing inter-fn (like `create-ngram-token-filter`) in `create-analyzer` and have it work in client - server. Also, datalevin.core cannot require datalevin.interpret, so we would need to move these fns to another ns to avoid the circular dependency I guess... What do you think?
resolves #105
> add token filters and regexp-tokenizer

- src/datalevin/storage.cljc
> Correct `update-schema` call

- src/datalevin/core.cljc
- src/datalevin/db.cljc
`tx-data->staged-report` Returns a transaction report without side-effects or changes to the db.
Clean branch, continuation from https://github.com/juji-io/datalevin/pull/136
> feat(tx-data->staged-report)

- src/pod/huahaiy/datalevin.clj
`entity` fn is missing from the list of exposed pod functions
> Adding `entity` to exposed pod functions

- native/resources/META-INF/native-image/org.clojars.huahaiy/datalevin-native/native-image.properties
the `--verbose` option in the file generates an error in recent version of native builder, as it should only be specified on the command line. This breaks compilation. Removing the switch from the properties file fixes the problem, and is backward compatible with older versions (at least in the sense that compilation won't break).
> Remove the --verbose from native properties file 

- src/datalevin/parser.cljc
- src/datalevin/query.cljc
timeouts used to compute deadlines (absolute instants) at parsing time.... and this gets cached. I modified the code so that timeouts are not converted to deadlines at parsing time.
> fix caching issue with timeouts

- src/datalevin/db.cljc
This fixes two typos in `DB`s `print-method` that lead to an error printing db at the REPL or serializing stack traces:
```clojure
@conn
Error printing return value (IllegalArgumentException) at clojure.core/-cache-protocol-fn (core_deftype.clj:584).
No implementation of method: :db-name of protocol: #'datalevin.storage/IStore found for class: nil
```
> fix print method

- src/datalevin/main.clj
This supports the use case of users who have values with tagged literals stored in their databases. Just as with `clojure.core/*data-readers*` and `clojure.core/default-data-readers`, there is also a static var containing the default readers to fall back to in contexts where the dynamic value has been rebound, which is used to initialize the dynamic var.
Tested locally with `lein test` - no issues.
I am not sure if the naming of `datalevin-data-readers` is unwieldy, but I named those vars like that to avoid potentially shadowing the equivalent vars from `clojure.core`. They can be renamed to something different if it would be better.
> Create dynamic var for data readers

- test/datalevin/main_test.cljc
Picking up where PR #187 left off, here is a test case that demonstrates the error I encountered as well as a fix by rebinding the newly dynamic `*datalevin-data-readers*`.
> Add test case for tagged literals + overriding default Datalevin readers.

- src/datalevin/core.cljc
- src/datalevin/lmdb.cljc
```
WARNING: load already refers to: #'clojure.core/load in namespace: datalevin.lmdb, being replaced by: #'datalevin.lmdb/load
WARNING: load already refers to: #'clojure.core/load in namespace: datalevin.core, being replaced by: #'datalevin.core/load
```
for reference I am using `tool.deps` + `tools.build`, not sure if lein users have the error or not
> getting clojure.core redefinition warnings when requiring datalevin

- src/datalevin/pull_api.cljc
- test/datalevin/test/pull_api.cljc
Addresses https://github.com/juji-io/datalevin/issues/224
I played with the implementation for a bit and was going to add a new frame record type `SinglevalRefAttrFrame`
but then realized the existing `MultivalRefAttrFrame` would work as well because its two cond cases work for cardinality one as well, when it finds the attribute: 
https://github.com/juji-io/datalevin/blob/c55574a8749eb5e4f787840301cede7b7f3f58dd/src/datalevin/pull_api.cljc#L88C10-L88C10
and when it doesn't https://github.com/juji-io/datalevin/blob/c55574a8749eb5e4f787840301cede7b7f3f58dd/src/datalevin/pull_api.cljc#L102 
- this last else is the same as the current version of pull which just calls `ref-frame` for a cardinality-one reference [here](https://github.com/juji-io/datalevin/blob/c55574a8749eb5e4f787840301cede7b7f …
> Bugfix: xform is called for cardinality/one refs in pull

- src/datalevin/pull_api.cljc
- test/datalevin/test/pull_api.cljc
My prior fix to add support for xform of cardinality-one ref types in this PR https://github.com/juji-io/datalevin/pull/226 
doesn't work for reverse component refs, I noticed this after seeing the same issue being fixed in DataScript 
https://github.com/tonsky/datascript/commit/941c2b172d631b5aeec181837132376e818554f1
and issue https://github.com/tonsky/datascript/issues/455
This PR reverts my prior attempt at a fix and pulls in the DataScript fix.
> Refactor xform to one refs in pull expressions

- src/datalevin/storage.cljc
- test/datalevin/test/transact.cljc
`:validate-data? true` doesn't work for some types.
Some type mismatches can cause `b/indexable` to throw an error before validation happens. This error doesn't happen when you pass a string instead of a UUID, which is why the current tests don't catch this.
This fix moves validation to be called before `b/indexable`.
I've added more tests cases to capture this issue.
Let me know if you want me to make any changes.
> Fix `:validate-data? true` not working for some types

- src/datalevin/core.cljc
- src/datalevin/storage.cljc
- test/datalevin/test/transact.cljc
Not sure if this is something that datalevin wants to support. So feel free to close this PR if it's not something that aligns with the datalevin vision.
**Rationale**
Coming from datomic I was finding one of the first things I do when I use datalevin is add some basic schema validation to prevent transacting entity attributes that are not defined in the schema.
**Proposed solution**
This PR adds the `:closed-schema?` flag. Which can be used to prevent entity attributes that have not been defined from being transacted. This is useful when you want to prevent accidental pollution of your data and/or interact with low trust or volatile sources.
Example:
```
(let [sc {:id      {:db/valueType :db.type/uuid}
:company {}}
db (d/empty-db "foo" sc {:closed-schema? true})]
(d/db-with db
[{:db/id …
```
> Add :closed-schema? option

- src/datalevin/binding/graal.clj
- src/datalevin/binding/java.clj
- src/datalevin/storage.cljc
- test/datalevin/test/transact.cljc
When using 0.8.26 there were some spacing issues with the invalid data error messages. 
```
Execution error (ExceptionInfo) at datalevin.storage/insert-data (storage.cljc:616).
Invalid data, expecting:db.type/longgot"foo"
```
This PR fixes the spacing.
```
Execution error (ExceptionInfo) at datalevin.storage/insert-data (storage.cljc:616).
Invalid data, expecting :db.type/long got "foo"
```
I also found some inconsistencies with the Invalid data error messages in other parts of the codebase. So updated those too.
Let me know if I need to make any changes.
> Fix spacing in invalid data error messages

- src/datalevin/storage.cljc
Knowing the attribute and value that caused the error is useful for handling the error, logging, debugging etc.
This should have been part of https://github.com/juji-io/datalevin/pull/237 but I overlooked it. 
Also fixed the `or` formatting to match the convention in datalevin.
> Add data to :closed-schema? error

- src/datalevin/db.clj
`reverse` was needed as entities was a list. Now that the collection is a vector, reverse is not needed. fixes https://github.com/juji-io/datalevin/issues/244
> fix optimization regression and redundant call

- src/datalevin/binding/java.clj
Hi,
datalevin 0.9 throws "Unsupported OS FreeBSD" on FreeBSD.
FreeBSD provides a package and a port for lmdb, currently at version 0.9.32.1
see https://www.freshports.org/databases/lmdb/.
This patch checks whether the file liblmdb.so exists in the canonical location and points the system property "lmdbjava.native.lib" at it.  If the file does not exist it throws with a reminder to install the package.
I added the function `use-os-package` instead of adding it to the platform detection in `extract-lmdb` because it would make the function name `extract-lmdb` misleading.
Running `lein test`, all tests pass on FreeBSD 14.0 amd64.
> Use FreeBSD package manager provided liblmdb.

- src/datalevin/parser.clj
- src/datalevin/query.clj
- test/datalevin/query_test.clj
- test/datalevin/test/parser_where.clj
This is the start of a fix for #288. However, it seems there are two levels of caching. The query results are cached and parsing the query is also cached. Why my test still currently fails.
I've fixed the first level of caching (the result caching) by adding a fn-object to the key. However, the query caching will be more challenging to fix as we need to parse the query to resolve the functions, and if we're parsing the query then there's not much point caching parsing the query.
One solution would be remove the query caching completely (but keep the fix for result caching):
```
(defn- parsed-q
[q]
(or (.get ^LRUCache *query-cache* q)
(let [res (dp/parse-query q)]
(.put ^LRUCache *query-cache* q res)
res)))
```
Would become:
```
(defn- parsed-q
[q]
(dp/parse-query q))
```
However, thinking …
> Fix for 288

- src/datalevin/parser.clj
- src/datalevin/query.clj
- test/datalevin/query_test.clj
- test/datalevin/test/parser_where.clj
As mentioned [here](
https://github.com/juji-io/datalevin/pull/289#issuecomment-2434447388) I realised there was a simple way to keep the query cache and prevent function implementation changes from returning stale results from the result cache.
It looks like currently this is only needed for functions in `:where` clause as functions in `:find` clause don't seem to have the same problem. However, they might in future so I've extended the test to catch potential future regressions where `:find` function implementation changes cause stale results.
Apologies for not seeing this solution the first time round.
EDIT: Forgot to mention micro benchmarking (usual benchmarking caveats). From what I could see the query parsing cache definitely makes a difference. As you said compared to results …
> Add query caching back #288 #289

- CHANGELOG.md
Congrats with the new release(s), exciting stuff!
I was reading the changelog and I was interested in the issues mentioned, but I could not click on the issue numbers. I think this change makes it easier to navigate the changelog. [Here is a preview](https://github.com/jeroenvandijk/datalevin/blob/a503c04858384246a58921de8d09d7612d251374/CHANGELOG.md)
It is basically a find and replace with the following regexp:
```
" \#(\d+)" => " [#$1](https://github.com/juji-io/datalevin/issues/$1)"
```
Feel free to ignore if you don't find this an improvement.
> Create links to issues mentioned in CHANGELOG.md

- doc/limits.md
Latest release bumps minimum JVM to 11.
> Docs: JVM 8 -> 11

- doc/vector.md
Hello
I've been testing the vector features for the last few days and I have some feedback that may or may not be useful.
Feel free to ignore if it's no longer relevant :^)
Thank you for the great work! 🚀
---
**No index is created if the vector attribute is namespaced**
`io.github.juji-io/datalevin {:git/sha "9a14b5992acae4f2bbdc741ea23c9213be4328be"}`
I tried to use `:kudos.chunk/content_markdown-embedding` as a vector attribute, but when I did no vector index was created. Changing to `:content_markdown-embedding` resulted in the index being created as expected.
**Some queries stall and cause heap exhaustion**
`io.github.juji-io/datalevin {:git/sha "9a14b5992acae4f2bbdc741ea23c9213be4328be"}`
```
(comment
;; This query is instant:
(time (d/q '[:find [?md]
:in $ ?emb-q
:where …
```
> Vector database feedback
